# Generated by Django 2.0.5 on 2018-08-23 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180823_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summary_p',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
