# Generated by Django 2.0.5 on 2018-08-24 13:27

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180824_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='', validators=[news.validators.validate_file_extension]),
        ),
    ]
