# Generated by Django 2.0.5 on 2018-08-24 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180824_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='summary_p',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
